// This file was generated by img2gb, DO NOT EDIT

#ifndef _ALCHEMIST_TILEMAP_H
#define _ALCHEMIST_TILEMAP_H

extern const UINT8 ALCHEMIST_TILEMAP[];
#define ALCHEMIST_TILEMAP_WIDTH 12
#define ALCHEMIST_TILEMAP_HEIGHT 12


#endif
