// This file was generated by img2gb, DO NOT EDIT

#ifndef _BATTLEFIELD_TILESET_H
#define _BATTLEFIELD_TILESET_H

extern const UINT8 BATTLEFIELD_TILESET[];
#define BATTLEFIELD_TILESET_TILE_COUNT 43


#endif
