// This file was generated by img2gb, DO NOT EDIT

#ifndef _BLACKSMITH_TILESET_H
#define _BLACKSMITH_TILESET_H

extern const UINT8 BLACKSMITH_TILESET[];
#define BLACKSMITH_TILESET_TILE_COUNT 81


#endif
