// This file was generated by img2gb, DO NOT EDIT

#ifndef _BOSS_ATTACK_TILEMAP_H
#define _BOSS_ATTACK_TILEMAP_H

extern const UINT8 BOSS_ATTACK_TILEMAP[];
#define BOSS_ATTACK_TILEMAP_WIDTH 12
#define BOSS_ATTACK_TILEMAP_HEIGHT 12


#endif
