// This file was generated by img2gb, DO NOT EDIT

#ifndef _CENTER_FAR_TILEMAP_H
#define _CENTER_FAR_TILEMAP_H

extern const UINT8 CENTER_FAR_TILEMAP[];
#define CENTER_FAR_TILEMAP_WIDTH 4
#define CENTER_FAR_TILEMAP_HEIGHT 4


#endif
