// This file was generated by img2gb, DO NOT EDIT

#ifndef _CENTER_NEAR_TILEMAP_H
#define _CENTER_NEAR_TILEMAP_H

extern const UINT8 CENTER_NEAR_TILEMAP[];
#define CENTER_NEAR_TILEMAP_WIDTH 8
#define CENTER_NEAR_TILEMAP_HEIGHT 8


#endif
