// This file was generated by img2gb, DO NOT EDIT

#include <types.h>

const UINT8 DOOR_OPENED_RIGHT_SIDE_TILEMAP[] = {
    0x2B,
    0x43,
    0x43,
    0x43,
    0x43,
    0x43,
    0x43,
    0x43,
    0x91,
    0xA0,
};
