// This file was generated by img2gb, DO NOT EDIT

#include <types.h>

const UINT8 DOOR_CLOSED_RIGHT_SIDE_TILEMAP[] = {
    0x2B,
    0x41,
    0x52,
    0x52,
    0x62,
    0x52,
    0x52,
    0x52,
    0x8F,
    0x9E,
};
