// This file was generated by img2gb, DO NOT EDIT

#include <types.h>

const UINT8 DOOR_OPENED_LEFT_SIDE_TILEMAP[] = {
    0x2A,
    0x42,
    0x42,
    0x42,
    0x42,
    0x42,
    0x42,
    0x42,
    0x90,
    0x9F,
};
