// This file was generated by img2gb, DO NOT EDIT

#include <types.h>

const UINT8 DOOR_CLOSED_LEFT_SIDE_TILEMAP[] = {
    0x2A,
    0x40,
    0x51,
    0x51,
    0x51,
    0x51,
    0x51,
    0x51,
    0x8E,
    0x9D,
};
