// This file was generated by img2gb, DO NOT EDIT

#ifndef _INN_TILEMAP_H
#define _INN_TILEMAP_H

extern const UINT8 INN_TILEMAP[];
#define INN_TILEMAP_WIDTH 12
#define INN_TILEMAP_HEIGHT 12


#endif
