// This file was generated by img2gb, DO NOT EDIT

#ifndef _KNIGHT_TILEMAP_H
#define _KNIGHT_TILEMAP_H

extern const UINT8 KNIGHT_TILEMAP[];
#define KNIGHT_TILEMAP_WIDTH 12
#define KNIGHT_TILEMAP_HEIGHT 12


#endif
