// This file was generated by img2gb, DO NOT EDIT

#ifndef _LEFT_NEAR_SIDE_TILEMAP_H
#define _LEFT_NEAR_SIDE_TILEMAP_H

extern const UINT8 LEFT_NEAR_SIDE_TILEMAP[];
#define LEFT_NEAR_SIDE_TILEMAP_WIDTH 2
#define LEFT_NEAR_SIDE_TILEMAP_HEIGHT 8


#endif
