// This file was generated by img2gb, DO NOT EDIT

#ifndef _LEFT_SIDE_TILEMAP_H
#define _LEFT_SIDE_TILEMAP_H

extern const UINT8 LEFT_SIDE_TILEMAP[];
#define LEFT_SIDE_TILEMAP_WIDTH 2
#define LEFT_SIDE_TILEMAP_HEIGHT 12


#endif
