// This file was generated by img2gb, DO NOT EDIT

#ifndef _LEFT_FAR_SIDE_TILEMAP_H
#define _LEFT_FAR_SIDE_TILEMAP_H

extern const UINT8 LEFT_FAR_SIDE_TILEMAP[];
#define LEFT_FAR_SIDE_TILEMAP_WIDTH 1
#define LEFT_FAR_SIDE_TILEMAP_HEIGHT 4


#endif
