// This file was generated by img2gb, DO NOT EDIT

#ifndef _RIGHT_FAR_SIDE_TILEMAP_H
#define _RIGHT_FAR_SIDE_TILEMAP_H

extern const UINT8 RIGHT_FAR_SIDE_TILEMAP[];
#define RIGHT_FAR_SIDE_TILEMAP_WIDTH 1
#define RIGHT_FAR_SIDE_TILEMAP_HEIGHT 4


#endif
