// This file was generated by img2gb, DO NOT EDIT

#ifndef _RIGHT_SIDE_TILEMAP_H
#define _RIGHT_SIDE_TILEMAP_H

extern const UINT8 RIGHT_SIDE_TILEMAP[];
#define RIGHT_SIDE_TILEMAP_WIDTH 2
#define RIGHT_SIDE_TILEMAP_HEIGHT 12


#endif
